In [18]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.9.0'

# Tensorflow 자료형

## tf.constant

In [3]:
sess=tf.Session()

In [13]:
# 초기화 되면서 메모리 크기와 type이 결정
# 세션 실행 시 자동으로 초기화 
# 고정된 크기 
a=tf.constant([5])
b=tf.constant([10.0,20,30])
c=tf.constant([10,20,30],dtype=tf.float32)

## tf.placeholder

In [14]:
# 학습 및 테스트 데이터를 담는 그릇 역할 / 자료구조만 정해주고, 나중에 data를 공급받음 / 반복적으로 feeding가능 
# 가변 / 갯수의 크기가 정해져 있지 않음
x=tf.placeholder(dtype=tf.float32)
input_data=[1,2,3,4,5]
sess.run(x,feed_dict={x:input_data})

array([1., 2., 3., 4., 5.], dtype=float32)

## tf.Variable

In [15]:
# constant처럼 고정된 크기의 메모리 공간
# 반복적으로 읽고 쓰기 가능 / 반드시 초기화 되어야함
input_data=[1,2,3,4,5]
w=tf.Variable(input_data,dtype=tf.float32)
init=tf.global_variables_initializer()
sess.run(init)

In [16]:
# 텐서 정보 입력 & 그래프 
x=tf.placeholder(dtype=tf.float32)
w=tf.Variable([2.0])
b=tf.constant([1.4])
y=w*x+b

init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

out1=sess.run(y,feed_dict={x:[1,2,3]})
out2=sess.run(y,feed_dict={x:[-1.0,-2.0]})

# 텐서 생성

In [7]:
a=tf.constant(2.0)
print(a)
# 결과값 읽어오기
print(sess.run(a))

Tensor("Const_1:0", shape=(), dtype=float32)
2.0


In [10]:
# 한 행이여서 0차원이다
a.shape

TensorShape([])

In [11]:
# 대괄호는 벡터라는 뜻 
b=tf.constant([2.0])
print(sess.run(b))

[2.]


In [16]:
m=tf.constant([[1,2],[3,4],[5,6]])
print(m)
print(m.shape[0])
print(sess.run(m))
# sess run을 하면 numpy로 변함
print(type(sess.run(m)))

Tensor("Const_7:0", shape=(3, 2), dtype=int32)
3
[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [19]:
a=tf.constant(np.array([1,2,3,4,5,6]),shape=(2,3))
print(sess.run(a))

[[1 2 3]
 [4 5 6]]


In [21]:
# 주어진 크기보다 작을 경우 가장 마지막 원소가 자동으로 채워짐
print(sess.run(tf.constant([0,1,2],shape=[4,2])))

[[0 1]
 [2 2]
 [2 2]
 [2 2]]


In [22]:
a=tf.constant([[1,2,3]],shape=[3,1])

In [24]:
sess.run(a)

array([[1],
       [2],
       [3]])

In [26]:
# 텐서의 자세한 정보
print(a.op)

name: "Const_11"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
        dim {
          size: 3
        }
        dim {
          size: 1
        }
      }
      tensor_content: "\001\000\000\000\002\000\000\000\003\000\000\000"
    }
  }
}



In [27]:
a=tf.constant([1,2,3])
b=tf.constant([3,5,6])
c=a>b
print(sess.run(c))

[False False False]
